export default {
  login: "majedul-dev",
  id: 46629448,
  node_id: "MDQ6VXNlcjQ2NjI5NDQ4",
  avatar_url: "https://avatars2.githubusercontent.com/u/46629448?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/majedul-dev",
  html_url: "https://github.com/majedul-dev",
  followers_url: "https://api.github.com/users/majedul-dev/followers",
  following_url:
    "https://api.github.com/users/majedul-dev/following{/other_user}",
  gists_url: "https://api.github.com/users/majedul-dev/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/majedul-dev/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/majedul-dev/subscriptions",
  organizations_url: "https://api.github.com/users/majedul-dev/orgs",
  repos_url: "https://api.github.com/users/majedul-dev/repos",
  events_url: "https://api.github.com/users/majedul-dev/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/majedul-dev/received_events",
  type: "User",
  site_admin: false,
  name: "Majedul Islam",
  company: null,
  blog: "https://majedulislam.co/",
  location: "Magura, Khulna, Bangladesh",
  email: null,
  hireable: null,
  bio: "I do modern web application design and development.",
  twitter_username: "mazedul_dev",
  public_repos: 15,
  public_gists: 11,
  followers: 79,
  following: 26,
  created_at: "2019-01-12T16:17:32Z",
  updated_at: "2020-07-27T11:19:43Z",
};
